services:
  - type: web
    name: movie-match-api
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false